language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-ssl-validator
  api_key:
    secure: HZyFNfiGMn3vDvjQ82hD04n7MRST+gJ1d6SP4JgRw81zBeWXpGNrc6OeqdaLTzKw+DNNFXFs5LU/6W7POJ6oK4JL6C04ARkk/4hGDyOQQCQ88TnfifWMGFiAli9yaukiJDDseU3VHLzdsdD7oUSJsNR5kvOvbwAYghE874rexmFHSCTLu40skn9VkxLgJ5495ZjxwuWpCHI5dbTS6gsyJCxdtuSHrrcWBK6oHCtNwyxap7tzfMlCa+DwQFnWhBpZ/RSaqovTeZOiAEhHyjRSP7qxneQDiGbmUE71kQJnpELENUnHaPvfY9nXhZw4wBjMSDy//iwGb9wvI329XwBgx0BAbWkYPNsEb3MAc5vbbaLhfFM9vZ3rJbkx6bz4e1LROjHIMxQhu3gcIMG3w2q4pVUxJbeZiW+DCU5dscVc0OKeAbW7c/qFdUSICzAXLTcozqX1gM2mv9+21Q68IbPd9qN1D1/KEpXE09HgZ7VvElnr4Hlg7LlOKoV0sFDLlG/4yDkqtTo34y1m7PybqwNLDRVJDDQv0CDOHqTFFW7PueSa9b+MfHF0VrIAxyfd8iVvXDZ2T0861SXDX0GQM21v4tlgDej5ejSVMleJ25icVCGYg5+OrgLTrWc0hh9b/Ppmj8i3i1ml5PL05HpIgnnv9iI4CH7Mu1czbz9tKmSGGcI=
notifications:
  slack:
    secure: EW3H6fk+KronvmE57cmuYVOoZNd3NLAB2U+8qWxWijqrYWZELmGROFZGXmWZJ86ENXz0uHpefxdW1PlgKflaKJ4AZcxFZwEgxgf1sbHslN+50zaSiS8uGmXE9P1FduDXwd9L1Qapwb8VsJaXPINVtdSHgAaUy/74yc6WwroVfq02vUn98KgsHcTNl9749CBlbdImt06US3Qr0F9O9DTUcyyKvhRXFN/MLv26+c/6c4tUIJcNLFXU0u/92MCmM6qYlEAi44jEdjQuCAmAFFdjH3Bnr65ruDq4UNM/G70BrYcY25EgRS2DvV2be5LC1KuWCZFtJ48f17bg56A8VV596EPUyllgWKmiiOf3GUpwTj8ooG3rn3b1ZjAu2DnOMSrVkJH/tKW77SMu9bi7yYrIHIILpHuMMOJ0VpSu4OAXbGIZyIluK4U3qXzEBiyxhXeIQF+OzXsPHbMWcPPmvSPo1zHuVdxSiPxLBU7538aTaLkXhCEkmXvIxK/Y1pYS6r3H69jTRlMygXzq4f1Ywj0HR+L8Hqmg6tj5+SN2CxLQC+TuyMsqDVmpEtFUYcAeB3HdOn5kII82x64M07j7oy1rStQBwyRLEMMqY9lsBzWip975IfTm+FnmSF0HuwpwK4T9ti5Yd+JZ/7k8UzBUH3559J7V0zetvuPlh0dhW65isKA=
