language: node_js
node_js: 8
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-ssl-validator
  api_key:
    secure: UMs/Z3fe4Ny1tx+4jSdRnFq+h+kZYgQ/Th+pg8qOLekMnxVMgdPg+B1sP0Mt0K4Oe0NvrAaw+1MJhR32ogO5sqvVXV2lY6rmHD6fjIQZ88gUEn00i9R79kQhDLi2d0xAz/NxvySIYqHDoKmwfZT8hIO0L39AV3MDywLnJcQwwONILo5FHPr1PtQJz/q9m1WChKSkhjSkENyjNWo6Tt2U9cNd2pJUxIlKdvqh9WzjBcczyYbMadd/Ufimp9YkhadjdUYF17BkbriqFmzct12LDKPhOOTfc6Oq5i4kSznkVKkhWx6YVivYv79hWd03y185E+ZN/Ns4kHOFnt6RN6vaMLtRugAuel1T4SwwgSHJDGQxi47XFv72HKVPmHvmCxZ6q8khzhpX1HRrbIhvWq2AjtWOhvxIJ4IlJIDoOZ8H4/s+A69afzgTxPIFPlSIU6UEiTyxvusvvrYrhFuQc/Bt0G8LuuT90BdqE1fb6OADDdFmbkk4un6rM30sMRx6rsu6iMTa7QCp3b90DwemP3Pa/3ewuCD1HaBxeCa+g1NZoeNpZIsym133pji1voSmOpUDyMDnq+M01ADGx36eX8iGj0aFA55iYJCgkWpz5LqgmqycROFfH+TIm3VZmnSh3iaGxxSM3tBFp3Hxwu6WT23UKHwW0kSKbo1QHQr+WF1a2Z8=
notifications:
  slack:
    secure: EW3H6fk+KronvmE57cmuYVOoZNd3NLAB2U+8qWxWijqrYWZELmGROFZGXmWZJ86ENXz0uHpefxdW1PlgKflaKJ4AZcxFZwEgxgf1sbHslN+50zaSiS8uGmXE9P1FduDXwd9L1Qapwb8VsJaXPINVtdSHgAaUy/74yc6WwroVfq02vUn98KgsHcTNl9749CBlbdImt06US3Qr0F9O9DTUcyyKvhRXFN/MLv26+c/6c4tUIJcNLFXU0u/92MCmM6qYlEAi44jEdjQuCAmAFFdjH3Bnr65ruDq4UNM/G70BrYcY25EgRS2DvV2be5LC1KuWCZFtJ48f17bg56A8VV596EPUyllgWKmiiOf3GUpwTj8ooG3rn3b1ZjAu2DnOMSrVkJH/tKW77SMu9bi7yYrIHIILpHuMMOJ0VpSu4OAXbGIZyIluK4U3qXzEBiyxhXeIQF+OzXsPHbMWcPPmvSPo1zHuVdxSiPxLBU7538aTaLkXhCEkmXvIxK/Y1pYS6r3H69jTRlMygXzq4f1Ywj0HR+L8Hqmg6tj5+SN2CxLQC+TuyMsqDVmpEtFUYcAeB3HdOn5kII82x64M07j7oy1rStQBwyRLEMMqY9lsBzWip975IfTm+FnmSF0HuwpwK4T9ti5Yd+JZ/7k8UzBUH3559J7V0zetvuPlh0dhW65isKA=
